#
# Copyright (C) 2024 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/sharp/Pucci

# APEX
DEXPREOPT_GENERATE_APEX_IMAGE := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := kryo385

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := kryo385

TARGET_USES_64_BIT_BINDER := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := Pucci
TARGET_NO_BOOTLOADER := true

# Dtbo
BOARD_KERNEL_SEPARATED_DTBO := true

# Display
TARGET_SCREEN_DENSITY := 480

# DRM
TARGET_ENABLE_MEDIADRM_64 := true

# Graphics
TARGET_USES_GRALLOC1 := true
TARGET_USES_HWC2 := true
TARGET_USES_ION := true

# Kernel
BOARD_KERNEL_CMDLINE := \
	androidboot.configfs=true \
	androidboot.console=ttyMSM0 \
	androidboot.hardware=qcom \
	androidboot.selinux=permissive \
	androidboot.usbcontroller=a600000.dwc3 \
	console=ttyMSM0,115200n8 \
	earlycon=msm_geni_serial,0xA84000 \
	ehci-hcd.park=3 \
	loop.max_part=7 \
	lpm_levels.sleep_disabled=1 \
	msm_rtb.filter=0x237 \
	service_locator.enable=1 \
	swiotlb=2048 \
	video=vfb:640x400,bpp=32,memsize=3072000

BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET := 0x01000000

BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_CONFIG := pucci_defconfig
TARGET_KERNEL_SOURCE := kernel/sharp/pucci
 
# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
PUCCI_PREBUILT := device/sharp/Pucci-prebuilt

TARGET_PREBUILT_KERNEL := $(PUCCI_PREBUILT)/Image.gz-dtb
BOARD_PREBUILT_DTBOIMAGE := $(PUCCI_PREBUILT)/dtbo.img

BOARD_ODM_KERNEL_MODULES += $(wildcard $(PUCCI_PREBUILT)/modules/odm/*.ko)
BOARD_VENDOR_KERNEL_MODULES += $(wildcard $(PUCCI_PREBUILT)/modules/vendor/*.ko)
endif

# OTA assert
TARGET_OTA_ASSERT_DEVICE := Pucci

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144 # (BOARD_KERNEL_PAGESIZE * 64)

BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 33554432
BOARD_ODMIMAGE_PARTITION_SIZE := 536870912
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 1610612736
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560
BOARD_VENDORIMAGE_PARTITION_SIZE := 1073741824

BOARD_PUCCI_PARTITION_LIST := odm product system vendor
BOARD_PARTITION_LIST := $(call to-upper, $(BOARD_PUCCI_PARTITION_LIST))
$(foreach p, $(BOARD_PARTITION_LIST), $(eval BOARD_$(p)IMAGE_FILE_SYSTEM_TYPE := ext4))

TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := sdm845
TARGET_BOARD_PLATFORM_GPU := qcom-adreno630

# QCOM
BOARD_USES_QCOM_HARDWARE := true

# Recovery
BOARD_USES_RECOVERY_AS_BOOT := true
TARGET_NO_RECOVERY := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.qcom
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_USERIMAGES_USE_EXT4 := true

# RenderScript
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so

# Security patch level
VENDOR_SECURITY_PATCH := 2021-09-01

# Treble
BOARD_VNDK_VERSION := current
BOARD_VENDOR := sharp

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
